;Custom_OpenClash_Rules_EN
;Complete Clash template with DNS leak protection
;Author: https://github.com/Aethersailor
;Project Address：https://github.com/Aethersailor/Custom_OpenClash_Rules
;Based on the original ACL4SSR template, thank you!
;See the settings below for the optimal Clash configuration
;https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%A1%88

[custom]
;Rule order is from top to bottom.
;Repeated rules have zero effect, changing the order will change the routing.

;本地地址和域名直连
ruleset=🎯 Direct Connection,[]GEOSITE,private
ruleset=🎯 Direct Connection,[]GEOIP,private,no-resolve
;本项目收录的直连规则
ruleset=🎯 Direct Connection,clash-domain:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Domain.yaml,28800
ruleset=🎯 Direct Connection,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Classical_IP.yaml,28800
;本项目收录的代理规则
ruleset=🚀 Proxy,clash-domain:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Domain.yaml,28800
ruleset=🚀 Proxy,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Classical_IP.yaml,28800
;谷歌在国内可用的域名直连
ruleset=🎯 Direct Connection,[]GEOSITE,google-cn
;国内游戏域名直连
ruleset=🎯 Direct Connection,[]GEOSITE,category-games@cn
;Steam 下载 CDN 直连
ruleset=🎯 Direct Connection,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Steam_CDN_Classical.yaml,28800
;各大游戏平台下载域名直连
ruleset=🎯 Direct Connection,[]GEOSITE,category-game-platforms-download
;BT Tracker 相关域名直连
ruleset=🎯 Direct Connection,[]GEOSITE,category-public-tracker
;即时通讯包括了 Telegram/WhatsApp/Line 等海外主流即时通讯软件域名
ruleset=💬 Messaging,[]GEOSITE,category-communication
;社交媒体包括了 Twitter(X)/Facebook/Instagram 等海外主流社交媒体
ruleset=🌐 Social Media,[]GEOSITE,category-social-media-!cn
ruleset=🤖 ChatGPT,[]GEOSITE,openai
ruleset=🤖 AI Services,[]GEOSITE,category-ai-!cn
ruleset=🚀 GitHub,[]GEOSITE,github
;测速工具包括 SpeedTest 等主流测速工具域名
ruleset=🚀 Speedtests,[]GEOSITE,category-speedtest
ruleset=🎮 Steam,[]GEOSITE,steam
ruleset=📹 YouTube,[]GEOSITE,youtube
ruleset=🎥 AppleTV+,[]GEOSITE,apple-tvplus
ruleset=🍎 Apple,[]GEOSITE,apple
ruleset=Ⓜ️ Microsoft Services,[]GEOSITE,microsoft
ruleset=📢 Google Notifications,[]GEOSITE,googlefcm
ruleset=🇬 Google,[]GEOSITE,google
ruleset=🎶 TikTok,[]GEOSITE,tiktok
ruleset=🎥 Netflix,[]GEOSITE,netflix
ruleset=🎥 DisneyPlus,[]GEOSITE,disney
ruleset=🎥 HBO,[]GEOSITE,hbo
ruleset=🎥 PrimeVideo,[]GEOSITE,primevideo
;Emby 包括主流 Emby 服务相关域名
ruleset=🎥 Emby,[]GEOSITE,category-emby
ruleset=🎻 Spotify,[]GEOSITE,spotify
ruleset=📺 Bahamut,[]GEOSITE,bahamut
ruleset=🎮 Gaming,[]GEOSITE,category-games
ruleset=🌎 Streaming Services,[]GEOSITE,category-entertainment
ruleset=🛒 Shopping Sites,[]GEOSITE,category-ecommerce
ruleset=🚀 Proxy,[]GEOSITE,gfw
ruleset=💬 Messaging,[]GEOIP,telegram,no-resolve
ruleset=🌐 Social Media,[]GEOIP,twitter,no-resolve
ruleset=🌐 Social Media,[]GEOIP,facebook,no-resolve
ruleset=🇬 Google,[]GEOIP,google,no-resolve
ruleset=🎥 Netflix,[]GEOIP,netflix,no-resolve
;由于 OpenClash 使用的大陆白名单收录不全，此处留有 geosite:cn 作为国内域名兜底
ruleset=🎯 Direct Connection,[]GEOSITE,cn
;由于 OpenClash 使用的大陆白名单收录不全，此处留有 geoip:cn 作为国内 IP 兜底
ruleset=🎯 Direct Connection,[]GEOIP,cn,no-resolve
;以上兜底规则会根据实际情况随时取消
;PT/BT 优化开启会使 80/443 以外端口的流量直连
ruleset=🔀 Other Ports,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Port_Direct.yaml,28800
;国内冷门域名会命中漏网之鱼，如影响使用，请设置漏网之鱼直连
;漏网之鱼直连时，无法通过 DNS 泄露测试，但是并不存在泄露
ruleset=🐟 Everything Else,[]FINAL
;设置规则标志位结束

;设置节点分组标志位
custom_proxy_group=🚀 Proxy`select`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=♻️ Automatic`url-test`.*`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=💬 Messaging`select`[]🚀 Proxy`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`[]🎯 Direct Connection
custom_proxy_group=🌐 Social Media`select`[]🚀 Proxy`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`[]🎯 Direct Connection`.*
custom_proxy_group=🚀 GitHub`select`[]🚀 Proxy`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`[]🎯 Direct Connection
custom_proxy_group=🤖 ChatGPT`select`[]🚀 Proxy`[]♻️ Automatic`[]🇸🇬 SG Servers`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🤖 AI Services`select`[]🚀 Proxy`[]♻️ Automatic`[]🇸🇬 SG Servers`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🎶 TikTok`select`[]🚀 Proxy`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=📹 YouTube`select`[]🚀 Proxy`[]♻️ Automatic`[]🇸🇬 SG Servers`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🎥 Netflix`select`[]🚀 Proxy`[]♻️ Automatic`[]🇸🇬 SG Servers`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🎥 DisneyPlus`select`[]🚀 Proxy`[]♻️ Automatic`[]🇸🇬 SG Servers`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🎥 HBO`select`[]🚀 Proxy`[]♻️ Automatic`[]🇸🇬 SG Servers`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🎥 PrimeVideo`select`[]🚀 Proxy`[]♻️ Automatic`[]🇸🇬 SG Servers`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🎥 AppleTV+`select`[]🚀 Proxy`[]♻️ Automatic`[]🇸🇬 SG Servers`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`[]🎯 Direct Connection`.*
custom_proxy_group=🎥 Emby`select`[]🚀 Proxy`[]♻️ Automatic`[]🎯 Direct Connection`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🎻 Spotify`select`[]🚀 Proxy`[]♻️ Automatic`[]🎯 Direct Connection`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=📺 Bahamut`select`[]🇼🇸 TW Servers`[]🚀 Proxy`[]🎯 Direct Connection`.*
custom_proxy_group=🌎 Streaming Services`select`[]🚀 Proxy`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🛒 Shopping Sites`select`[]🚀 Proxy`[]♻️ Automatic`[]🎯 Direct Connection`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=📢 Google Notifications`select`[]🚀 Proxy`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers
custom_proxy_group=🇬 Google`select`[]🚀 Proxy`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🍎 Apple`select`[]🎯 Direct Connection`[]🚀 Proxy`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=Ⓜ️ Microsoft Services`select`[]🎯 Direct Connection`[]🚀 Proxy`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🎮 Gaming`select`[]🎯 Direct Connection`[]🚀 Proxy`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🎮 Steam`select`[]🎯 Direct Connection`[]🚀 Proxy`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🚀 Speedtests`select`[]🚀 Proxy`[]🎯 Direct Connection`[]♻️ Automatic`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🐟 Everything Else`select`[]🚀 Proxy`[]♻️ Automatic`[]🎯 Direct Connection`[]🇭🇰 HK Servers`[]🇺🇸 US Servers`[]🇯🇵 JP Servers`[]🇸🇬 SG Servers`[]🇼🇸 TW Servers`[]🇰🇷 KR Servers`.*
custom_proxy_group=🔀 Other Ports`select`[]🐟 Everything Else`[]🎯 Direct Connection
custom_proxy_group=🇭🇰 HK Servers`url-test`(🇭🇰|港|\bHK(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|hk|Hong Kong|HongKong|hongkong|HONG KONG|HONGKONG|深港|HKG|九龙|Kowloon|新界|沙田|荃湾|葵涌)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇺🇸 US Servers`url-test`(🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|纽纽|亚特兰大|迈阿密|华盛顿|\bUS(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|United States|UnitedStates|UNITED STATES|USA|America|AMERICA|JFK|EWR|IAD|ATL|ORD|MIA|NYC|LAX|SFO|SEA|DFW|SJC)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 JP Servers`url-test`(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|\bJP(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Japan|JAPAN|JPN|NRT|HND|KIX|TYO|OSA|关西|Kansai|KANSAI)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇸🇬 SG Servers`url-test`(🇸🇬|新加坡|坡|狮城|\bSG(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Singapore|SINGAPORE|SIN)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇼🇸 TW Servers`url-test`(🇹🇼|🇼🇸|台|新北|彰化|\bTW(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Taiwan|TAIWAN|TWN|TPE|ROC)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇰🇷 KR Servers`url-test`(🇰🇷|\bKR(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Korea|KOREA|KOR|首尔|韩|韓|春川|Chuncheon|ICN)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🎯 Direct Connection`select`[]DIRECT
;设置分组标志位

;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true

